### ISSUE TITLE
Wrong values in the hover view

### ISSUE THREAD

**Issue by sergburn** [stef-levesque/vscode-hexdump#49]
I'm getting very weird data in the hover view, screenshots attached. VSCode version 1.28.2, hexdump version 1.7.0.
1. Selecting first 4 bytes: 8-16 bit integers are all 0, 32-bit value is not correct..
Expected: uint8: 2 (0x02), uint16: 43266 (0xA902), uint32: 3 084 953 858 (0xB7E0A902)
<img width="723" alt="hexdump-nib2-off0-select" src="https://user-images.githubusercontent.com/1159466/47998740-0d5db380-e109-11e8-876e-31acc3bd63bb.png">

2. Hovering on 2nd byte: again, short types are 0's, 4-byte value is wrong.
Expected: uint8: 169 (0xA9), uint16: 57 513 (0xE0A9), uint32: 1 522 000 041 (0x5AB7E0A9)
<img width="706" alt="hexdump-nib2-off1-hover" src="https://user-images.githubusercontent.com/1159466/47998741-0d5db380-e109-11e8-871d-fa3bb4e92454.png">

3. Selecting bytes 1-5: Same invalid result
<img width="717" alt="hexdump-nib2-off1-select" src="https://user-images.githubusercontent.com/1159466/47998742-0d5db380-e109-11e8-865b-c5760e9f1c76.png">

4. 2-byte view, hovering first byte
<img width="615" alt="hexdump-nib4-off0-hover" src="https://user-images.githubusercontent.com/1159466/47998743-0d5db380-e109-11e8-9699-bfc751e12264.png">

5. 4-byte view, hovering first byte
<img width="627" alt="hexdump-nib8-off0-hover" src="https://user-images.githubusercontent.com/1159466/47998744-0df64a00-e109-11e8-879a-3385ac8295be.png">

Any idea on what may cause this problem?

**Comment by stef-levesque** [comment]
I don't see this issue on macOS, on which OS are you seeing this ?

**Comment by stef-levesque** [comment]
Was happening only on small files due to a bad ArrayBuffer conversion.
Fixed with version 1.7.1

**Comment by sergburn** [comment]
Yes, I'm using macOS as well (10.13.6). The file was indeed quite small, just 49 bytes.
Thanks a lot for fixing it!!

Just one question, with "hexdump.showInspector": false a small pop-up with text "Loading..." still appears while hovering in hex view. Is it triggered by hexdump or some other extension?

**Comment by stef-levesque** [comment]
Seems VSCode doesn’t expect the hover provider to return a Promise with undefined. I’ll make a quick fix.

**Comment by stef-levesque** [comment]
Fixed in version 1.7.2. Should be available soon.

**Comment by sergburn** [comment]
Yep, works like a charm, thank you!
